# Generated by Django 5.0.6 on 2024-06-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_book_genre_remove_book_year_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
